inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Enforce Ruby 3.1+ hash shorthand syntax
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: always

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

# Disable block length for specs
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
